### PR TITLE
Adding picoCAD

### PR DESCRIPTION
**Pull request by denilsonsa**
(And removing a trailing whitespace from the previous line.)

### CODE REVIEW

**Comment by felipebueno** [comment]
Wow, this picoCAD thing is awesome!

Thanks for the PR, @denilsonsa!

**Comment by filipedeschamps** [comment]
WOW!!! Really awesome 😳

**Comment by felipebueno** [comment]
Hey, @filipedeschamps!

I've seen you on YouTube! :smile: 

Didn't know you're into PICO-8. Maybe you could make a video on it someday. It's a great way to introduce people to programming and pixel-art.

**Comment by filipedeschamps** [comment]
For sure!!! 😍  🤝 👍

**Pull request merged**
